In [1]:
import cv2
import numpy as np
from dataloader import Trial
import matplotlib.pyplot as plt

In [ ]:
video_path = r'..\data\TH8\TH8ST17A3D250TS0_2.mov'

In [3]:
recording = Trial(video_path)

In [7]:
print(recording[0])

[[ 1  1  1 ...  0  0  0]
 [ 1  1  1 ...  0  0  0]
 [ 1  1  1 ...  0  0  0]
 ...
 [94 95 92 ... 86 83 85]
 [91 93 89 ... 84 80 83]
 [89 91 87 ... 83 79 82]]


In [ ]:
# recording.to_gray(inplace=True)
# recording.gauss_blur(ksize=(5,5), sigmaX=9, inplace=True)
recording.to_gray(inplace=True).gauss_blur(ksize=(5,5), sigmaX=9, inplace=True);

In [5]:
cv2.imshow("Teehee", recording[-1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
recording.play_video()